logLevel = "DEBUG"
defaultEntryPoints = ["web", "websecure"]

# Entry Points Configuration
[entryPoints]

  [entryPoints.web]
    address = ":80"
#     [entryPoints.web.http.redirections.entrypoint]
#     to = "websecure"
#     scheme = "https"
#     #permanent = true

  [entryPoints.websecure]
    address = ":443"


# API Configuration
[api]
  insecure = true
  dashboard = true
  debug = true

# Docker Provider
[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedByDefault = true
